lib/sitefinanceiro_web/router.ex
defmodule SitefinanceiroWeb.Router do
  use SitefinanceiroWeb, :router

  import SitefinanceiroWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SitefinanceiroWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  ## Authentication routes

  scope "/", SitefinanceiroWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    #get "/login", PersonController, :index
    #get "/cadastro", PersonController, :new

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    #get "/users/reset_password", UserResetPasswordController, :new
    #post "/users/reset_password", UserResetPasswordController, :create
    #get "/users/reset_password/:token", UserResetPasswordController, :edit
    #put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SitefinanceiroWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/financial", FinancialController, :index
    get "/financial/new", FinancialController, :new
    get "/financial/reports", FinancialController, :reports

    resources "/receitas", ReceitaController
    resources "/despesas", DespesaController

    live "/receitas2", Receita2Live.Index, :index
    live "/receitas2/new", Receita2Live.Index, :new
    live "/receitas2/:id/edit", Receita2Live.Index, :edit

    live "/receitas2/:id", Receita2Live.Show, :show
    live "/receitas2/:id/show/edit", Receita2Live.Show, :edit

    live "/despesas2", Despesa2Live.Index, :index
    live "/despesas2/new", Despesa2Live.Index, :new
    live "/despesas2/:id/edit", Despesa2Live.Index, :edit

    live "/despesas2/:id", Despesa2Live.Show, :show
    live "/despesas2/:id/show/edit", Despesa2Live.Show, :edit
    #get "/users/settings", UserSettingsController, :edit
    #put "/users/settings", UserSettingsController, :update
    #get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", SitefinanceiroWeb do
    pipe_through [:browser]

    get "/", HomeController, :index

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update

  end

  # Other scopes may use custom stacks.
  # scope "/api", SitefinanceiroWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: SitefinanceiroWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end


end

lib/sitefinanceiro_web/live/despesa2_live/form_component.ex
defmodule SitefinanceiroWeb.Despesa2Live.FormComponent do
  use SitefinanceiroWeb, :live_component

  alias Sitefinanceiro.Timeline2

  @impl true
  def update(%{despesa2: despesa2} = assigns, socket) do
    changeset = Timeline2.change_despesa2(despesa2)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"despesa2" => despesa2_params}, socket) do
    changeset =
      socket.assigns.despesa2
      |> Timeline2.change_despesa2(despesa2_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"despesa2" => despesa2_params}, socket) do
    aux_despesa2_params = %{description: despesa2_params["description"], value: despesa2_params["value"], user_id: socket.assigns.idAux}
    
    save_despesa2(socket, socket.assigns.action, aux_despesa2_params)
  end

  defp save_despesa2(socket, :edit, despesa2_params) do
    case Timeline2.update_despesa2(socket.assigns.despesa2, despesa2_params) do
      {:ok, _despesa2} ->
        {:noreply,
         socket
         |> put_flash(:info, "Despesa2 updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_despesa2(socket, :new, despesa2_params) do
    case Timeline2.create_despesa2(despesa2_params) do
      {:ok, _despesa2} ->
        {:noreply,
         socket
         |> put_flash(:info, "Despesa2 created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/sitefinanceiro_web/live/despesa2_live/index.ex
defmodule SitefinanceiroWeb.Despesa2Live.Index do
  use SitefinanceiroWeb, :live_view

  alias Sitefinanceiro.Timeline2
  alias Sitefinanceiro.Timeline2.Despesa2

  @impl true
  def mount(_params, session, socket) do
    if connected?(socket), do: Timeline2.subscribe()

    user = Sitefinanceiro.Accounts.get_user_by_session_token(session["user_token"])
    #IO.inspect(user.id)
    {:ok, assign(socket, despesas2: list_despesas2(user.id), user: user), temporary_assigns: [despesas2: []]}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Despesa2")
    |> assign(:despesa2, Timeline2.get_despesa2!(id))
    |> assign(:user, socket.assigns.user)
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Despesa2")
    |> assign(:despesa2, %Despesa2{})
    |> assign(:user, socket.assigns.user)
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Despesas2")
    |> assign(:despesa2, nil)
    |> assign(:user, socket.assigns.user)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    despesa2 = Timeline2.get_despesa2!(id)
    {:ok, _} = Timeline2.delete_despesa2(despesa2)

    {:noreply, assign(socket, :despesas2, list_despesas2(socket.assigns.user.id))}
  end

  @impl true
  def handle_info({:despesa2_created, despesa2}, socket) do
    IO.inspect("oi2")
    IO.inspect(socket.assigns.user)
    {:noreply, update(socket, :despesas2, fn despesas2 -> [despesa2 | despesas2] end)}
  end

  def handle_info({:despesa2_updated, despesa2}, socket) do
    {:noreply, update(socket, :despesas2, fn despesas2 -> [despesa2 | despesas2] end)}
  end

  defp list_despesas2(id) do
    Timeline2.list_despesas2(id)
  end
end

lib/sitefinanceiro_web/live/despesa2_live/show.ex
defmodule SitefinanceiroWeb.Despesa2Live.Show do
  use SitefinanceiroWeb, :live_view

  alias Sitefinanceiro.Timeline2

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:despesa2, Timeline2.get_despesa2!(id))}
  end

  defp page_title(:show), do: "Show Despesa2"
  defp page_title(:edit), do: "Edit Despesa2"
end

lib/sitefinanceiro_web/live/live_helpers.ex
defmodule SitefinanceiroWeb.LiveHelpers do
  import Phoenix.LiveView
  import Phoenix.LiveView.Helpers

  alias Phoenix.LiveView.JS

  @doc """
  Renders a live component inside a modal.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <.modal return_to={Routes.receita2_index_path(@socket, :index)}>
        <.live_component
          module={SitefinanceiroWeb.Receita2Live.FormComponent}
          id={@receita2.id || :new}
          title={@page_title}
          action={@live_action}
          return_to={Routes.receita2_index_path(@socket, :index)}
          receita2: @receita2
        />
      </.modal>
  """
  def modal(assigns) do
    assigns = assign_new(assigns, :return_to, fn -> nil end)

    ~H"""
    <div id="modal" class="phx-modal fade-in" phx-remove={hide_modal()}>
      <div
        id="modal-content"
        class="phx-modal-content fade-in-scale"
        phx-click-away={JS.dispatch("click", to: "#close")}
        phx-window-keydown={JS.dispatch("click", to: "#close")}
        phx-key="escape"
      >
        <%= if @return_to do %>
          <%= live_patch "✖",
            to: @return_to,
            id: "close",
            class: "phx-modal-close",
            phx_click: hide_modal()
          %>
        <% else %>
          <a id="close" href="#" class="phx-modal-close" phx-click={hide_modal()}>✖</a>
        <% end %>

        <%= render_slot(@inner_block) %>
      </div>
    </div>
    """
  end

  defp hide_modal(js \\ %JS{}) do
    js
    |> JS.hide(to: "#modal", transition: "fade-out")
    |> JS.hide(to: "#modal-content", transition: "fade-out-scale")
  end
end

lib/sitefinanceiro_web/live/receita2_live/form_component.ex
defmodule SitefinanceiroWeb.Receita2Live.FormComponent do
  use SitefinanceiroWeb, :live_component

  alias Sitefinanceiro.Timeline

  @impl true
  def update(%{receita2: receita2} = assigns, socket) do
    changeset = Timeline.change_receita2(receita2)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"receita2" => receita2_params}, socket) do
    changeset =
      socket.assigns.receita2
      |> Timeline.change_receita2(receita2_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"receita2" => receita2_params}, socket) do
    aux_receita2_params = %{description: receita2_params["description"], value: receita2_params["value"], user_id: socket.assigns.idAux}

    save_receita2(socket, socket.assigns.action, aux_receita2_params)
  end

  defp save_receita2(socket, :edit, receita2_params) do
    case Timeline.update_receita2(socket.assigns.receita2, receita2_params) do
      {:ok, _receita2} ->
        {:noreply,
         socket
         |> put_flash(:info, "Receita2 updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_receita2(socket, :new, receita2_params) do
    case Timeline.create_receita2(receita2_params) do
      {:ok, _receita2} ->
        {:noreply,
         socket
         |> put_flash(:info, "Receita2 created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/sitefinanceiro_web/live/receita2_live/index.ex
defmodule SitefinanceiroWeb.Receita2Live.Index do
  use SitefinanceiroWeb, :live_view

  alias Sitefinanceiro.Timeline
  alias Sitefinanceiro.Timeline.Receita2

  @impl true
  def mount(_params, session, socket) do
    if connected?(socket), do: Timeline.subscribe()

    user = Sitefinanceiro.Accounts.get_user_by_session_token(session["user_token"])
    #IO.inspect(user.id)
    {:ok, assign(socket, receitas2: list_receitas2(user.id), user: user), temporary_assigns: [receitas2: []]}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Receita2")
    |> assign(:receita2, Timeline.get_receita2!(id))
    |> assign(:user, socket.assigns.user)
  end

  defp apply_action(socket, :new, _params) do
    IO.inspect(socket.assigns.user)
    
    socket
    |> assign(:page_title, "New Receita2")
    |> assign(:receita2, %Receita2{})
    |> assign(:user, socket.assigns.user)
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Receitas2")
    |> assign(:receita2, nil)
    |> assign(:user, socket.assigns.user)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    receita2 = Timeline.get_receita2!(id)
    {:ok, _} = Timeline.delete_receita2(receita2)

    {:noreply, assign(socket, :receitas2, list_receitas2(socket.assigns.user.id))}
  end

  @impl true
  def handle_info({:receita2_created, receita2}, socket) do
    IO.inspect("oi2")
    IO.inspect(socket.assigns.user)
    {:noreply, update(socket, :receitas2, fn receitas2 -> [receita2 | receitas2] end)}
  end

  def handle_info({:receita2_updated, receita2}, socket) do
    {:noreply, update(socket, :receitas2, fn receitas2 -> [receita2 | receitas2] end)}
  end

  defp list_receitas2(id) do
    Timeline.list_receitas2(id)
  end
end

lib/sitefinanceiro_web/live/receita2_live/show.ex
defmodule SitefinanceiroWeb.Receita2Live.Show do
  use SitefinanceiroWeb, :live_view

  alias Sitefinanceiro.Timeline

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:receita2, Timeline.get_receita2!(id))}
  end

  defp page_title(:show), do: "Show Receita2"
  defp page_title(:edit), do: "Edit Receita2"
end

lib/sitefinanceiro_web/live/receita2_live/form_component.html.heex
<div>
  <h2><%= @title %></h2>

  <.form
    let={f}
    for={@changeset}
    id="receita2-form"
    phx-target={@myself}
    phx-change="validate"
    phx-submit="save">
  
    <div class="row mb-3">
      <div class="col">
        <%= label f, :description, class: "form-label" %>
        <%= text_input f, :description, class: "form-control" %>
        <%= error_tag f, :description %>
      </div>
      <div class="col">   
        <%= label f, :value, class: "form-label" %>
        <%= number_input f, :value, step: "any", class: "form-control" %>
        <%= error_tag f, :value %>
      </div>
    </div>
      
    <div class="text-center" style="margin-top: 20px">
      <%= submit "Save", phx_disable_with: "Saving...", class: "btn btn-success", style: "width: 150px" %>
    </div>
  </.form>
</div>

lib/sitefinanceiro_web/live/receita2_live/index.html.heex
<div class="container">

  <h1>Listando Receitas Live View</h1>

  <%= if @live_action in [:new, :edit] do %>
    <.modal return_to={Routes.receita2_index_path(@socket, :index)}>
      <.live_component
        module={SitefinanceiroWeb.Receita2Live.FormComponent}
        id={@receita2.id || :new}
        title={@page_title}
        idAux={@user.id}
        action={@live_action}
        receita2={@receita2}
        return_to={Routes.receita2_index_path(@socket, :index)}
      />
    </.modal>
  <% end %>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Descrição</th>
            <th>Valor (R$)</th>

            <th></th>
          </tr>
        </thead>
        <tbody id="receitas2" phx-update="prepend">
          <%= for receita2 <- @receitas2 do %>
            <tr id={"receita2-#{receita2.id}"}>
              <td><%= receita2.description %></td>
              <td><%= receita2.value %></td>

              <td>
                <span><%= live_redirect "Mostrar", to: Routes.receita2_show_path(@socket, :show, receita2), class: "btn btn-info" %></span>
                <span><%= live_patch "Editar", to: Routes.receita2_index_path(@socket, :edit, receita2), class: "btn btn-primary" %></span>
                <span><%= link "Deletar", to: "#", phx_click: "delete", phx_value_id: receita2.id, data: [confirm: "Are you sure?"], class: "btn btn-danger" %></span>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
  <div class="text-center">
    <span><%= live_patch "Criar Receita Live View", to: Routes.receita2_index_path(@socket, :new), class: "btn btn-success" %></span>
  </div>
  <div class="text-center" style="margin-top: 20px">
    <span><%= link "Ver Relatórios", to: Routes.financial_path(@socket, :reports), class: "btn btn-primary" %></span>
  </div>
</div>

lib/sitefinanceiro_web/live/receita2_live/show.html.heex
<h1>Mostrar Receita Live View</h1>

<%= if @live_action in [:edit] do %>
  <.modal return_to={Routes.receita2_show_path(@socket, :show, @receita2)}>
    <.live_component
      module={SitefinanceiroWeb.Receita2Live.FormComponent}
      id={@receita2.id}
      title={@page_title}
      action={@live_action}
      receita2={@receita2}
      return_to={Routes.receita2_show_path(@socket, :show, @receita2)}
    />
  </.modal>
<% end %>

<ul>

  <li>
    <strong>Description:</strong>
    <%= @receita2.description %>
  </li>

  <li>
    <strong>Value:</strong>
    <%= @receita2.value %>
  </li>

</ul>

<span><%= live_patch "Edit", to: Routes.receita2_show_path(@socket, :edit, @receita2), class: "button" %></span> |
<span><%= live_redirect "Back", to: Routes.receita2_index_path(@socket, :index) %></span>