lib/sitefinanceiro_web/router.ex
defmodule SitefinanceiroWeb.Router do
  use SitefinanceiroWeb, :router

  import SitefinanceiroWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SitefinanceiroWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  ## Authentication routes

  scope "/", SitefinanceiroWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    #get "/login", PersonController, :index
    #get "/cadastro", PersonController, :new

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    #get "/users/reset_password", UserResetPasswordController, :new
    #post "/users/reset_password", UserResetPasswordController, :create
    #get "/users/reset_password/:token", UserResetPasswordController, :edit
    #put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SitefinanceiroWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/financial", FinancialController, :index
    get "/financial/new", FinancialController, :new
    get "/financial/reports", FinancialController, :reports

    resources "/receitas", ReceitaController
    resources "/despesas", DespesaController

    live "/receitas2", Receita2Live.Index, :index
    live "/receitas2/new", Receita2Live.Index, :new
    live "/receitas2/:id/edit", Receita2Live.Index, :edit

    live "/receitas2/:id", Receita2Live.Show, :show
    live "/receitas2/:id/show/edit", Receita2Live.Show, :edit

    live "/despesas2", Despesa2Live.Index, :index
    live "/despesas2/new", Despesa2Live.Index, :new
    live "/despesas2/:id/edit", Despesa2Live.Index, :edit

    live "/despesas2/:id", Despesa2Live.Show, :show
    live "/despesas2/:id/show/edit", Despesa2Live.Show, :edit
    #get "/users/settings", UserSettingsController, :edit
    #put "/users/settings", UserSettingsController, :update
    #get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", SitefinanceiroWeb do
    pipe_through [:browser]

    get "/", HomeController, :index

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update

  end

  # Other scopes may use custom stacks.
  # scope "/api", SitefinanceiroWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: SitefinanceiroWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end


end

lib/sitefinanceiro_web/views/layout_view.ex
defmodule SitefinanceiroWeb.LayoutView do
  use SitefinanceiroWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/sitefinanceiro_web/templates/layout/_user_menu.html.heex
<ul>
<%= if @current_user do %>
  <li><%= @current_user.email %></li>
  <li><%= link "Settings", to: Routes.user_settings_path(@conn, :edit) %></li>
  <li><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %></li>
<% else %>
  <li><%= link "Register", to: Routes.user_registration_path(@conn, :new) %></li>
  <li><%= link "Log in", to: Routes.user_session_path(@conn, :new) %></li>
<% end %>
</ul>

lib/sitefinanceiro_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/sitefinanceiro_web/templates/layout/footer.html.heex
<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">Programação Funcional - Unifor - 2022</span>
  </div>
</footer>

lib/sitefinanceiro_web/templates/layout/header.html.heex
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href={ }>Gestão Financeira</a>

      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse"
        aria-controls="navbarCollapse"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0" style="display:flex; justify-content:center; align-items:center">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href={ Routes.home_path(@conn, :index)  }>Home</a>
          </li>
          <%= if @current_user do %>
          
            <li class="nav-item">
              <%= link "Receitas", to: Routes.receita_path(@conn, :index), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link "Despesas", to: Routes.despesa_path(@conn, :index), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link "ReceitasLiveView", to: Routes.receita2_index_path(@conn, :index), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link "DespesasLiveView", to: Routes.despesa2_index_path(@conn, :index), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %>
            </li>
            
            <li class="nav-item">
              <p style="color: white; margin: 0 20px"><%= @current_user.email %></p>
            </li>
          
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href={ Routes.user_session_path(@conn, :new)  }>Login</a>
            </li>
          
          <% end %>
        </ul>
      </div>

    </div>
  </nav>
</header>

lib/sitefinanceiro_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/sitefinanceiro_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "Sitefinanceiro", suffix: " · Phoenix Framework" %>
    <link rel="stylesheet" href={Routes.static_path(@conn, "/assets/css/bootstrap.min.css")}/>
    <link rel="stylesheet" href={Routes.static_path(@conn, "/assets/css/signin.css")}/>
    <link rel="stylesheet" href={Routes.static_path(@conn, "/assets/css/sitefinanceiro.css")}/>

    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body class="d-flex flex-column h-100">
    <!-- render("header.html", conn: @conn) -->
    <%= render "header.html", assigns %>
    <%= @inner_content %>
    <%= render("footer.html")%>
    <script type="text/javascript" src={Routes.static_path(@conn, "/assets/js/bootstrap.min.js")}></script>
  </body>
</html>